# Generated by Django 4.2.3 on 2023-08-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_team_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('result', models.CharField(blank=True, choices=[('', 'Not Available'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('game1', models.CharField(blank=True, choices=[('Narrows - Capture The Flag', 'Narrows - Capture The Flag'), ('Heretic - Capture The Flag', 'Heretic - Capture The Flag'), ('The Pit - Capture The Flag', 'The Pit - Capture The Flag'), ('Construct - King Of The Hill', 'Construct - King Of The Hill'), ('Guardian - Oddball', 'Guardian - Oddball'), ('Onslaught - Capture The Flag', 'Onslaught - Capture The Flag')], max_length=50)),
                ('game2', models.CharField(blank=True, choices=[('Narrows - Slayer', 'Narrows - Slayer'), ('Heretic - Slayer', 'Heretic - Slayer'), ('The Pit - Slayer', 'The Pit - Slayer'), ('Construct - Slayer', 'Construct - Slayer'), ('Amplified - Slayer', 'Amplified - Slayer')], max_length=50)),
                ('game3', models.CharField(blank=True, choices=[('Narrows - Capture The Flag', 'Narrows - Capture The Flag'), ('Heretic - Capture The Flag', 'Heretic - Capture The Flag'), ('The Pit - Capture The Flag', 'The Pit - Capture The Flag'), ('Construct - King Of The Hill', 'Construct - King Of The Hill'), ('Guardian - Oddball', 'Guardian - Oddball'), ('Onslaught - Capture The Flag', 'Onslaught - Capture The Flag')], max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
            ],
        ),
    ]
