# Generated by Django 4.2.3 on 2023-08-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='challenger_additional_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='respondent_additional_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DisputeRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='dispute_screenshots/')),
                ('additional_evidence', models.URLField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeChallenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='dispute_screenshots/')),
                ('additional_evidence', models.URLField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
