# Generated by Django 4.2.3 on 2023-08-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_rename_disputechallenger_disputeproof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='team1_additional_evidence',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team1_claim',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team1_owner',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team1_screenshot',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team2_additional_evidence',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team2_claim',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team2_owner',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='team2_screenshot',
        ),
        migrations.AddField(
            model_name='dispute',
            name='team1_owner_proof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_owner_dispute', to='matches.disputeproof'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='team2_owner_proof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_owner_dispute', to='matches.disputeproof'),
        ),
    ]
