# Generated by Django 4.2.3 on 2023-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_remove_dispute_team1_additional_evidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disputeproof',
            old_name='screenshot',
            new_name='game1_screenshot',
        ),
        migrations.AddField(
            model_name='disputeproof',
            name='game2_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='dispute_screenshots/'),
        ),
        migrations.AddField(
            model_name='disputeproof',
            name='game3_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='dispute_screenshots/'),
        ),
    ]
