# Generated by Django 4.2.3 on 2023-08-14 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_rename_screenshot_disputeproof_game1_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeproof',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
