# Generated by Django 4.2.3 on 2023-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_disputeproof_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeproof',
            name='claim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
