# Generated by Django 4.2.3 on 2023-12-01 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_directchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
