# Generated by Django 4.2.3 on 2023-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_dispute_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dispute_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
