# Generated by Django 4.2.3 on 2023-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_match_dispute_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='search_only',
            field=models.BooleanField(default=False),
        ),
    ]
