# Generated by Django 4.2.3 on 2023-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_match_search_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='search_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='game1',
            field=models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='game2',
            field=models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='game3',
            field=models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50),
        ),
    ]
