# Generated by Django 4.2.3 on 2023-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_challenge_search_only_alter_match_game1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchallenge',
            name='search_only',
            field=models.BooleanField(default=False),
        ),
    ]
