# Generated by Django 4.2.3 on 2023-12-11 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_alter_matchsupport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsupport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
