# Generated by Django 4.2.3 on 2023-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_matchsupport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsupport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
