# Generated by Django 4.2.3 on 2023-12-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_matchsupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='controller_only',
            field=models.BooleanField(default=False),
        ),
    ]
