# Generated by Django 4.2.3 on 2023-12-18 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0027_challenge_controller_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_selected_players',
            field=models.ManyToManyField(blank=True, related_name='selected_for_team1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_selected_players',
            field=models.ManyToManyField(blank=True, related_name='selected_for_team2', to=settings.AUTH_USER_MODEL),
        ),
    ]
