# Generated by Django 4.2.3 on 2023-12-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_match_team1_selected_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1_selected_players',
            new_name='team1_players',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_selected_players',
            new_name='team2_players',
        ),
    ]
