# Generated by Django 4.2.3 on 2023-12-18 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0029_rename_team1_selected_players_match_team1_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_players',
            field=models.ManyToManyField(blank=True, related_name='selected_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
