# Generated by Django 4.2.3 on 2023-12-19 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0030_challenge_challenge_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchallenge',
            name='challenge_players',
            field=models.ManyToManyField(blank=True, related_name='selected_direct_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
