# Generated by Django 4.2.3 on 2023-12-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0031_directchallenge_challenge_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('squads', 'Squads')], default='squads', max_length=10),
        ),
    ]
