# Generated by Django 4.2.3 on 2023-07-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_owner_remove_team_players_team_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
