# Generated by Django 4.2.3 on 2023-08-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
    ]
