# Generated by Django 4.2.3 on 2023-08-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.FloatField(default=1000),
        ),
    ]
