# Generated by Django 4.2.3 on 2023-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
