# Generated by Django 4.2.3 on 2023-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_team',
            field=models.BooleanField(default=False),
        ),
    ]
