# Generated by Django 4.2.3 on 2023-08-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_full_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='disbanded',
            field=models.BooleanField(default=False),
        ),
    ]
