# Generated by Django 4.2.3 on 2023-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_eligible_team_eligible_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='at_capacity',
            field=models.BooleanField(default=False),
        ),
    ]
