# Generated by Django 4.2.3 on 2023-07-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_established'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
