# Generated by Django 4.2.3 on 2023-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mu',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='phi',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='profile',
            name='sigma',
            field=models.FloatField(default=0.06),
        ),
    ]
