# Generated by Django 4.2.3 on 2023-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_mu_profile_rating_remove_profile_phi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
