# Generated by Django 4.2.3 on 2023-08-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
