# Generated by Django 4.2.3 on 2023-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitch_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
