# Generated by Django 4.2.3 on 2023-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activision_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
