# Generated by Django 4.2.3 on 2023-12-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_activision_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='steam_avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steam_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steam_username',
        ),
    ]
