# Generated by Django 4.2.3 on 2023-12-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_profile_steam_avatar_remove_profile_steam_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
    ]
