# Generated by Django 4.2.3 on 2023-12-02 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_until_eligible',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
