# Generated by Django 4.2.3 on 2023-12-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_time_until_eligible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='time_until_eligible',
            new_name='eligible_at',
        ),
    ]
