# Generated by Django 4.2.3 on 2023-12-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_time_until_eligible_profile_eligible_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eligible',
            field=models.BooleanField(default=True),
        ),
    ]
