# Generated by Django 4.2.3 on 2023-12-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_badges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='photo',
            new_name='icon',
        ),
    ]
