# Generated by Django 4.2.3 on 2023-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_photo_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamertag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
