# Generated by Django 4.2.3 on 2023-12-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duos_teams', '0002_duosteaminvitation'),
        ('users', '0029_profile_psnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_duos_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duos_members', to='duos_teams.duosteam'),
        ),
    ]
