# Generated by Django 4.2.3 on 2023-12-27 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duos_teams', '0002_duosteaminvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('team1_result', models.CharField(blank=True, choices=[('', 'Not Available'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('team2_result', models.CharField(blank=True, choices=[('', 'Not Available'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('match_completed', models.BooleanField(default=False)),
                ('match_disputed', models.BooleanField(default=False)),
                ('dispute_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('search_only', models.BooleanField(default=False)),
                ('controller_only', models.BooleanField(default=False)),
                ('game1', models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50)),
                ('game2', models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50)),
                ('game3', models.CharField(blank=True, choices=[('Highrise - Control', 'Highrise - Control'), ('Invasion - Control', 'Invasion - Control'), ('Karachi - Control', 'Karachi - Control'), ('Scrapyard - Control', 'Scrapyard - Control'), ('Terminal - Control', 'Terminal - Control'), ('Highrise - Hardpoint', 'Highrise - Hardpoint'), ('Invasion - Hardpoint', 'Invasion - Hardpoint'), ('Karachi - Hardpoint', 'Karachi - Hardpoint'), ('Scrapyard - Hardpoint', 'Scrapyard - Hardpoint'), ('Terminal - Hardpoint', 'Terminal - Hardpoint'), ('Highrise - Search & Destroy', 'Highrise - Search & Destroy'), ('Invasion - Search & Destroy', 'Invasion - Search & Destroy'), ('Karachi - Search & Destroy', 'Karachi - Search & Destroy'), ('Scrapyard - Search & Destroy', 'Scrapyard - Search & Destroy'), ('Skidrow - Search & Destroy', 'Skidrow - Search & Destroy'), ('Terminal - Search & Destroy', 'Terminal - Search & Destroy')], max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duos_home_matches', to='duos_teams.duosteam')),
                ('team1_players', models.ManyToManyField(blank=True, related_name='duos_selected_for_team1', to=settings.AUTH_USER_MODEL)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duos_away_matches', to='duos_teams.duosteam')),
                ('team2_players', models.ManyToManyField(blank=True, related_name='duos_selected_for_team2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
