# Generated by Django 4.2.3 on 2023-12-27 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duos_teams', '0002_duosteaminvitation'),
        ('duos_matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('search_only', models.BooleanField(default=False)),
                ('controller_only', models.BooleanField(default=False)),
                ('challenge_players', models.ManyToManyField(blank=True, related_name='duos_selected_players', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duos_challenges', to='duos_teams.duosteam')),
            ],
        ),
    ]
