# Generated by Django 4.2.3 on 2023-12-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duos_matches', '0003_duosdirectchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_result', models.CharField(choices=[('', 'Not Available'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duos_matches.duosmatch')),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'team_owner')},
            },
        ),
    ]
