# Generated by Django 4.2.3 on 2023-12-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duos_matches', '0004_duosmatchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosDisputeProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField(blank=True, null=True)),
                ('game1_screenshot', models.ImageField(blank=True, null=True, upload_to='duos_dispute_screenshots/')),
                ('game2_screenshot', models.ImageField(blank=True, null=True, upload_to='duos_dispute_screenshots/')),
                ('game3_screenshot', models.ImageField(blank=True, null=True, upload_to='duos_dispute_screenshots/')),
                ('additional_evidence', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duos_matches.duosmatch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
