# Generated by Django 4.2.3 on 2024-01-02 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('duos_matches', '0007_duosmatch_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='duosdisputeproof',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
