# Generated by Django 4.2.3 on 2023-12-27 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos')),
                ('established', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.FloatField(default=1000)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('full_team', models.BooleanField(default=False)),
                ('at_capacity', models.BooleanField(default=False)),
                ('disbanded', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=False)),
                ('eligible_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duos_owned_teams', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='duos_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
